# Generated by Django 5.1 on 2024-08-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
